# Generated by Django 4.2.6 on 2023-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_active_book_author_book_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('rented', 'rented'), ('sold', 'sold'), ('available', 'available')], max_length=50, null=True),
        ),
    ]
