# Generated by Django 4.2.6 on 2023-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'sold'), ('rented', 'rented'), ('available', 'available')], max_length=50, null=True),
        ),
    ]
